### ISSUE TITLE
Deleting stale branches

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/maintenance#11]
Many of our HSF repos have stale branches (about 3-5 branches). Should we consider deleting the stale branches?

For future, maybe automate the process of deleting a branch when it is merged?

**Comment by klieret** [comment]
Yes, I'm sure they can be deleted. There's also gh actions for that. But I'd say this is very low on the list of priorities...

As with new PRs, there's a setting for that: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by amanmdesai** [comment]
agreed that its a very low priority work.  

it would be great to activate the new PR settings

**Comment by klieret** [comment]
Feel free to change it for the repositories you're working on :)

**Comment by amanmdesai** [comment]
Hi, 
I could not access the repositories setting.

So maybe you will have to change the setting whenever you can.

I can manually delete the stale branches if required.

**Comment by klieret** [comment]
Ah, that's true, that probably requires admin permissions... I'll do this these days

**Comment by amanmdesai** [comment]
hmm thank you.

**Comment by klieret** [comment]
Closing because low prio and not centrally enforcable
