### ISSUE TITLE
how about adding labels for index, setup and summary/glossary modules

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/maintenance#17]

**Comment by klieret** [comment]
summary is not a file but is auto generated I think

As for the others, I feel like there's rarely more than 1 issue associated to them, so it shouldn't come up too often.

With the episode labels, the idea is that people can check if someone else is currently assigned to something the same file so they can coordinate. Don't think this is so frequent for the other things.

**Comment by amanmdesai** [comment]
okay.

**Comment by klieret** [comment]
I'll close this for now but thank you for the suggestion :)
